### PR TITLE
make IDs optional, add ome_dataclass decorator

### PR DESCRIPTION
**Pull request by tlambert03**
This PR has us use our own `@ome_dataclass` decorator, which is a wrapper around `pydantic.dataclasses.dataclass`.  I've been working with custom dataclass decorators in napari recently and finding it useful/powerful.

This PR makes all of the "ID" fields optional, and if they are not provided, a valid ID will be autogenerated, incrementing from the previous IDs.  If one is provided, it is validated as usual.
```python
In [1]: from ome_types.model import Instrument   

In [2]: i = Instrument()  

In [3]: i.id                           
Out[3]: 'Instrument:1'
```

we could probably use this pattern to move other things from the `autogen.py`

### CODE REVIEW

**Comment by jmuhlich** [comment]
Would it work to store just an int with the highest observed numeric ID, rather than storing a set of all strings ever seen that needs to be scanned every time?

**Comment by jmuhlich** [comment]
I was thinking about how it might work to have a system for all References that would turn these ID-based implicit links into actual Python object references (probably using weakrefs under the hood). Doing this for the use case of reading from XML would be pretty straightforward, but I don't know what the "write" API should look like.

**Comment by tlambert03** [comment]
> Would it work to store just an int with the highest observed numeric ID, rather than storing a set of all strings ever seen that needs to be scanned every time?

no that would be far too reasonable :joy:
will do (or rather ... will look at and merge #24)

> I was thinking about how it might work to have a system for all References that would turn these ID-based implicit links into actual Python object references

yeah that sounds good too.  I'm having a hard time finding an example of a xml file that uses Refs... do you have one?  or are they all using refs and I'm missing it

**Comment by jmuhlich** [comment]
I tried out the idea of just keeping the max int ID and submitted a PR against this one. I'm not super happy with the logic flow with all of the if/elses but it was the best way I could come up with to avoid duplicating some of the logic.

**Comment by jmuhlich** [comment]
Check out `filter.ome.xml` in the test suite. The `FilterSet` is full of refs:
```xml
    <FilterSet ID="FilterSet:1" Manufacturer="Ink Inc." Model="Mk 3" LotNumber="K753">
      <ExcitationFilterRef ID="Filter:1"/>
      <ExcitationFilterRef ID="Filter:2"/>
      <ExcitationFilterRef ID="Filter:3"/>
      <ExcitationFilterRef ID="Filter:4"/>
      <DichroicRef ID="Dichroic:1"/>
      <EmissionFilterRef ID="Filter:5"/>
      <EmissionFilterRef ID="Filter:6"/>
    </FilterSet>
```

**Comment by tlambert03** [comment]
> I was thinking about how it might work to have a system for all References that would turn these ID-based implicit links into actual Python object references (probably using weakrefs under the hood). Doing this for the use case of reading from XML would be pretty straightforward, but I don't know what the "write" API should look like.

ok, haven't thought my way all the way through to the write API yet... but what do you think of this:
Everytime a model class (that has a `Ref` in the schema) is instantiated, we store a weakref from the id to the instance... and a `_dereference` method that returns an instance given a string.

```python
@ome_dataclass
class Filter(ManufacturerSpec):
    id: Optional[FilterID] = None

    _refs ClassVar[Dict[str, ReferenceType[Filter]]] = field(default_factory=dict)
    def __post_init__(self):
        # enforce session uniqueness?
        if self.id in Filter._refs:
            raise ValueError(f"Cannot use id: {self.id}")
        Filter._refs[self.id] = ref(self)
    
    def _dereference(self, id: str):
        if id in Filter._refs:
            return Filter._refs[id]()
        return None
        # or possibly raise exceptions 
```

Then anything that has an `_ref` field will have a corresponding `@property` without the `ref` that provides the list of deferenced items

```python
@ome_dataclass
class FilterSet(ManufacturerSpec):
    excitation_filter_ref: List[FilterRef] = field(default_factory=list)

    @property
    def emission_filters(self) -> List[Filter]:
        return [Filter._dereference(ref) for f in self.excitation_filter_ref]
```

**Comment by tlambert03** [comment]
I'm going to merge this PR, and take on the references in a new one.  It occured to me that with this PR making ids optional,  we can also get rid of this bit ugliness, which I'll do in a followup:
https://github.com/tlambert03/ome-types/blob/fa7d1fe9e4197c5b94637a29872f3afcc9c0e9ee/src/ome_autogen.py#L320-L329

**Comment by jmuhlich** [comment]
With the implicit version, the API would look just like what you outlined in your example with global state.

**Comment by tlambert03** [comment]
> Your proposal for managing the refs with global state will have problems if anyone needs to manage more than one model

ah, yeah makes sense.

> I don't see a great way to manage the refs except within the OME "root" object. 

also makes sense... wanna take a crack at it?  or does it still feel too cloudy?  It does seem like it'd be a nice feature!

**Comment by jmuhlich** [comment]
Which approach do you think would be best - explicit or implicit? I'm leaning toward the implicit to simplify the end-user API even though it will make the implementation hairier.

**Comment by tlambert03** [comment]
I also like the implicit approach better unless it gets _too_ hairy

**Pull request merged**
