### PR TITLE
Add bioformats XML reader

### PR DESCRIPTION
**Pull request by tlambert03**
This adds an optional bioformats metadata reader, using loci_tools to extract `OME` many more files than we currently can.

No new dependencies added to `setup.py` but this will require jpype, and download `loci_tools.jar` (once) if someone uses `from_bioformats`... 

possibly out of scope here?  but strictly opt-in...

### CODE REVIEW

**Comment by joshmoore** [comment]
TIL (or yesterday during the call): https://github.com/PolusAI/bfio

**Comment by jmuhlich** [comment]
I always get nervous when libraries download stuff from the internet at runtime... In Ashlar (where bioformats is admittedly a hard requirement) my strategy is to fetch a fixed version of `loci_tools.jar` at build time (sdist / develop / build_py). This way it gets packaged in the source dist on pypi and local dev environments will have it too, but I don't have to commit it to git. Would it be overly complicated to create a separate ome-types-bioformats package to package the jar the same way? Then our `bioformats` extra would just declare a dependency on that.

Regarding python-bioformats, last time I looked at it a few years ago it seemed narrowly focused on the use case of supporting CellProfiler on a compute cluster (and perhaps even more narrowly, specifically whatever the Broad was doing :joy:) and not general-purpose bioformats API access. Maybe it's changed since. I do think jpype and pyjnius do a pretty good job at transparent automatic mapping of Java APIs to Python, so a bespoke pythonic wrapper around bioformats didn't seem so worthwhile.

**Comment by tlambert03** [comment]
> Would it be overly complicated to create a separate ome-types-bioformats package to package the jar the same way?

yeah, it would be _generally_ cool to have that as a pypi/conda thing that we could all pull from (pims, napari-bioformats, ome-types, etc...)

**Comment by jmuhlich** [comment]
Have all of those projects settled on jpype? Should this ome-types-bioformats have a declared dependency on jpype? Is there any jpype-related boilerplate or helpful support code it should provide? I guess at the very least it should provide a function that calls `jpype.addClassPath` with the locally-packaged jar path? I suppose it doesn't need a dependency on any specific java bridge package and could offer support code for more than one of them.

**Comment by JacksonMaxfield** [comment]
Coming back to this to say after some thought, I would love to see a BioFormatsReader added as a rollback option to `aicsimageio`. Similar to our current import system.

if the user has `jpype` installed and all other readers fail (or if specifically requested) then `BioFormatsReader` gives the file a go. That would basically allow `aicsimageio` to optionally cover most of the bases and then add specific non-Java dependency readers later on if needed. That even pulls in some of this functionality in this PR.

Who knows if I will ever get around to it, just thinking out loud.

**Comment by tlambert03** [comment]
>I would love to see a BioFormatsReader added as a rollback option to aicsimageio
> Who knows if I will ever get around to it, just thinking out loud.

I think I'd like that best too!  I'd love to see `aicsimageio` be the go-to source for all things IO, "pure python if at all possible... but we gotchu if not" :joy:

maybe we can sync up sometime on zoom, and I can trouble you to give me a brief tour of the codebase, and where I might start hacking on it to help out?

**Comment by JacksonMaxfield** [comment]
> maybe we can sync up sometime on zoom, and I can trouble you to give me a brief tour of the codebase, and where I might start hacking on it to help out?

Would love to. We are trying to get a meeting on the books with the NIH team behind `bfio` too so maybe all of us can?

**Comment by tlambert03** [comment]
yep that sounds great.  happy to join.  ping me

**Comment by cgohlke** [comment]
I am concerned that depending on Bio-Formats, loci-tools, or aicsimageio (depends on copyleft libczi) would make this package practically GPL licensed unless one purchases commercial licenses of Bio-Formats and libczi or removes all code touching copyleft libraries from distributions.

**Comment by tlambert03** [comment]
Thanks for adding that @cgohlke.  Putting this functionality elsewhere (like aicsimageio) is the current "winning proposal".   I don't understand enough about the implications of licenses to say what it means for those repos... but I think it looks safe to say that it won't be going here.

**Comment by JacksonMaxfield** [comment]
Thanks for the reminder on license stuff. I have been meaning to add a section to the README of aicsimageio that says "certain readers are licensed under more or less strict requirements" and then a full list.

I believe LIF support is also GPL :disappointed:

**Comment by tlambert03** [comment]
https://github.com/AllenCellModeling/aicsimageio/releases/tag/v4.2.0

I've never been happier to close an issue un-merged! 🎉 

for those interested, see also `bioformats_jar` on [PyPI](https://pypi.org/project/bioformats-jar/) and [conda](https://anaconda.org/conda-forge/bioformats_jar).  Just the jar with a simple jpype wrapper ... so each new library doesn't need to re-invent the downloading and inclusion of the jar; but leaves the full implementation to whoever wants to depend on it.  Also includes type stubs!

**Comment by joshmoore** [comment]
> I've never been happier to close an issue un-merged! 🎉

;) :heart:

**Pull request closed without merging**
