### PR TITLE
Rename container fields to plural form

### PR DESCRIPTION
**Pull request by jmuhlich**

### CODE REVIEW

**Comment by tlambert03** [comment]
hmm, after looking at this, I'm less confident about not just using aliases.  Seems like a fair amount of hoops to jump through since we're basically changing up the schema.  I also don't know that I want to _force_ someone to have to use our internal methods to be able to create a valid class...  for instance, if someone uses `ome = ome_types.OME(**random_dict)` as long as that `random_dict` follows the naming of the OME schema, it should work.  (I'm aware we've already done some other things that may have broken that ... but I'd hesitate to go farther down that road, and I'd like to go back and fix it where we have broken it)

**Comment by jmuhlich** [comment]
Ok. Will give that a shot. I’ll submit it as a separate PR so we can still
have this branch for reference.

**Comment by tlambert03** [comment]
also feel free to disagree and provide a counter argument :)

**Comment by jmuhlich** [comment]
Hah, my proposal to do it as a second PR was my low key way of doing that. :P

**Comment by jmuhlich** [comment]
What are your design goals for doing this as aliases? Allow both singular and plural names in constructors? What about accessing or setting an aliased attribute on an already-constructed object?

Think about what a constructor signature would look like when there is an aliased field. Will there be an arg for both names? I don't think Python's typing hints can declare args as mutually exclusive.

I think users are more likely to be familiar with JSON data and other dict-type data structures than they are with the OME schema, and those tend to use plural names for containers. For example, the Amazon Web Services JSON schemas (a widely-used schema that I have fairly frequent contact with) use plurals. For some examples see here: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter . I feel that as long as we document that container names are pluralized users won't be confused. We could even provide a list of such fields in our docs. If we do a good job with this thing then users should be able to just browse our docs and tab-complete in their editor or Python repl to figure out what fields are available and what values to pass, rather than starting with the OME schema and working out how to translate that to our API.

**Comment by tlambert03** [comment]
no definitely wouldn't want both names in the constructor.  I was just envisioning adding an `@property` alias for each plural form.  You could also use a [`ClassVar`](https://docs.python.org/3/library/dataclasses.html#class-variables) to keep it out of the constructor signature... (but you'd still need a property to hook it to the alias).

But, I'm not too stuck on this, just wanted to discuss it a bit more.  I buy your arguments that not many people are going to care too much about a slight divergence from the OME schema... we can stick with this PR as is if it feels right to you.  If we (ever) have someone raise an issue we can reconsider at that point

**Comment by tlambert03** [comment]
I just sent you a collaborator invite.  So if you're done with this, see if it lets you merge

**Pull request merged**
