### PR TITLE
Fix serialization/deserialization of weakrefs

### LINKED ISSUE #60: Remove or replace call to weakref / support serdes
Hey @tlambert03 !

Back again, one of the checks we do on `aicsimageio` is to ensure that the `AICSImage` / the base `Reader` object can be fully serialized. This is largely useful for dask worker transfer (while it's not recommended to transfer a whole image between workers, it is in some cases useful, i.e. it is decently efficient to transfer a _not-yet-read_ image between workers for metadata parsing / some image handling).

Using the produced `OME` object from `from_xml` is awesome but unfortunately it can't be serialized due to [this `weakref` call / attr creator](https://github.com/tlambert03/ome-types/blob/master/src/ome_autogen.py#L266).

I have gotten our tests working locally by simply removing this `__post_init_post_parse__` function addition (or really just removing the entire `OME` object `CLASS_OVERRIDE`), but, it _is_ there so I am here to ask: _"Why?"_

Would it possible to remove this? I also know that the `__getstate__` and `__setstate__` [can be used to override default pickle calls](https://docs.python.org/3/library/pickle.html#object.__getstate__) if that is an option I could potentially work on a patch for adding those functions to allow pickling and unpickling of the `OME` object.

### PR DESCRIPTION
**Pull request by tlambert03**
fixes #60 and pickling of OME objects with weakrefs by adding  `__getstate__` and `__setstate__` methods that de-reference re-reference the weakrefs.

I added tests, and most of them are passing, but a handful of them with xml annotations are still failing with a very weird message:
```
_pickle.PicklingError: Can't pickle <class 'xml.etree.ElementTree.Element'>: it's not the same object as xml.etree.ElementTree.Element
```

furthermore, I don't get that error when I do the test manually in ipython.  @jmuhlich,  would love to hear if you have any thoughts on what might be happening there.

### CODE REVIEW

**Comment by jmuhlich** [comment]
Oh man I waged epic battle with that `xml.etree.ElementTree.Element` identity issue myself. I discovered that due to how `xml.etree.ElementTree` is implemented in C, every time you import classes from it in a different module of your own, you get distinct `class` objects. Instances of one such distinct class are not considered instances of any other instance. This means that when you create e.g. an `Element` object in one module, then pass it to a function in another module which calls `isinstance(elt, Element)`, it will return false. The way I dealt with it was to ensure our code only imports `xml.etree.ElementTree` in one module, then all our other modules import it from _there_. This isn't an issue in the actual module code since all XML handling is in one module, but it does impact the tests:
https://github.com/tlambert03/ome-types/blob/74103b1a7392717e0ad4b9b07fbb4a3c6c17e813/testing/test_model.py#L11-L12

The `PicklingError` is almost certainly a manifestation of this issue. I'm not sure if there's a way to influence how `pickle` obtains the class object to use when unpickling, and if there isn't one we'll need to re-serialize `XMLAnnotation` elements as XML strings for pickling. I agree that's not great, but at least it's not the entire XML document. XMLAnnotations seem pretty rare in the wild from what I've seen anyway.

**Comment by jmuhlich** [comment]
Even once we fix the ElementTree identity issue, there will still be an issue with the equality testing in `test_serialization`. `Element` objects don't define a custom `__eq__` method so even if you parse the same XML string twice, the resulting `Element` objects will not compare equal. We might need to implement a custom `__eq__` method on `XMLAnnotation` elements that re-serializes the `Element` and compares that.

**Comment by jmuhlich** [comment]
I think any direct pickling of `Element` objects is doomed. There seems to always be some sequence of imports of our code and `xml.etree` that leads to the PicklingError, and in the face of user code doing its own imports there's nothing we can do. It looks we'll need to use the XML string representation here for pickling, and due to `Element`'s lack of a custom `__eq__` we'll probably want to use the XML string for equality comparison as well (in a canonicalized form). Here are the two approaches I see right away:

**1. On-demand XML serialization in `XMLAnnotation.__getstate__` and `__eq__`, and XML re-parsing in `__setstate__`.**
This preserves our current XMLAnnotation model where `.value` is an `Element`. Performance of OME-XML parsing and generation is unchanged. Performance of code that interrogates the XML structure of XMLAnnotations also remains unchanged. Pickling/unpickling and `__eq__` will incur XML serialization/parsing overhead every time.

**2. Change the `XMLAnnotation` model so `value` holds an ahead-of-time canonicalized XML-serialized string.**
This will make pickling and equality just trivially work without any custom `__getstate__` or `__eq__` implementations since the XML data is all in a plain string, and they will be fast. We can still provide a `@property` that  builds an `Element` on demand at the cost of the XML re-parsing. The performance of OME-XML parsing in the presence of XMLAnnotations will be affected, since each XMLAnnotation will need to be re-serialized on the way in rather than just taking a direct reference to the already parsed `Element` object. OME-XML generation will be slower too because we'll need to re-parse on the way out. Accessing the `Element` will also be slowed down by the on-demand re-parse.

I'm not sure how much real-world performance is actually on the table here. It depends on 1) How many XMLAnnotations are present in a given workload of images and how complex their XML is, and 2) How much pickling/unpickling is done. Maybe the clarity of the code is more important... (My assumptions are that pickling/unpickling would occur only once per image in typical use cases, like sending images to worker processes, and model equality testing will be very rare. I think poking around in the XMLAnnotation Element content will be rare too, but I'm less certain of that.)

Sorry this has gotten pretty long. You guys let me know what you think, and if you can come up with any other solutions.

**Comment by tlambert03** [comment]
This is awesome, thanks for all the sleuthing @jmuhlich!  I guess I favor on-demand serialization in option #1: putting the performance penalty (however small/large) on the pickling and equality checking.  Feels like that's the less common operation, and the code would be a bit more sandboxed... You agree?

I added benchmarking in  #63  to help tell whether any of this really matters...

**Comment by tlambert03** [comment]
updated this PR with overrides for `__getstate__`, `__setstate__` and `__eq__` on `XMLAnnotation`.  Seems to be working with all roundtrip serialization tests passing now.  @jmuhlich, if you have a moment to take a quick look at the approach before merging, that'd be great.

thanks @JacksonMaxfield for raising this issue.  this is definitely a useful thing to be testing.

**Comment by JacksonMaxfield** [comment]
I just want to chime in and say this:

> The way I dealt with it was to ensure our code only imports xml.etree.ElementTree in one module, then all our other modules import it from there.

Is WILD.

**Comment by tlambert03** [comment]
agreed... that's A) some nonsense going on there in etree and B) incredible detective work!

**Comment by jmuhlich** [comment]
I agree it's wild, and it never sat right with me... You encouraged me to create a minimum reproducible example and figure out exactly what's going on! Turns out the culprit isn't `xml.etree`, it's `xmlschema`! I think this code is the issue but I'm still digging:
https://github.com/sissaschool/xmlschema/blob/master/xmlschema/etree.py#L24-L59
If we can figure out how to keep the `ElementTree` imports from getting messed up (maybe we just have to move our `ElementTree` import after our `xmlschema` import?) we might be able to avoid messing with `XMLAnnotation` pickling entirely! The custom `__eq__` will be required regardless, though.

**Comment by tlambert03** [comment]
wow...

**Comment by jmuhlich** [comment]
I have convinced myself there is definitely a bug in that module namespace manipulation code in `xmlschema`. I submitted a two-line fix at sissaschool/xmlschema#220 . From the pace that the developers there are closing issues and cutting new releases, I think there's a good chance this could make it into a published release quickly.

**Comment by jmuhlich** [comment]
I removed the new `XMLAnnotation` `__getstate__` and `__setstate__` methods and changed `__eq__` to use `ElementTree.tostring`, and that passes on py38 using my xmlschema fix. :) I guess we can move forward with this PR as it stands and then roll back the pickle part once xmlschema releases my fix?

Now that we're down to it, I'm not sure resolving the weakrefs is the best way to do this. I'm a little nervous about what happens when fragments of a model are pickled and not the top-level OME object. What about removing the `ref_` entirely from the pickled state, and re-running the code in `OME.__post_init_post_parse__` in `OME.__getstate__` to rebuild the weakrefs from the ID strings? Maybe the logic we have in `__post_init_post_parse__` should be moved to a method that can be called more easily from elsewhere. (Calling `__post_init_post_parse__` explicitly feels wrong)

**Comment by jmuhlich** [comment]
That proposed change means people could still pickle a fragment of a model, but any refs will be broken on unpickle. I think this would prevent the kinds of misuse of pickled model objects that I'd expect.

**Comment by tlambert03** [comment]
awesome.  thanks for the PR to xmlschema.  will be cool if that fixes other things too

> What about removing the ref_ entirely from the pickled state, and re-running the code in OME.__post_init_post_parse__ in OME.__getstate__ to rebuild the weakrefs from the ID strings

I'm happy to try that out before we commit to the approach in this PR.  will give it a go tomorrow.

**Comment by tlambert03** [comment]
looks like your fix is already merged at xmlschema.  I'm going to go ahead and merge this anyway so @JacksonMaxfield can at least use our master branch, and we can look at bumping our xmlschema requirement and cleaning it up in a later PR... perhaps before cutting a new release.

**Comment by tlambert03** [comment]
forgot to add... I made the change you suggested in https://github.com/tlambert03/ome-types/pull/61#issuecomment-750585787 (removing `refs` on __getstate__ and rebuilding them in `OME.__setstate__`).  works well, and I like it better

**Pull request merged**
